### ISSUE TITLE
Create redux store

### ISSUE THREAD

**Issue by cleverjack** [cleverjack/react-redux-book-list#1]
Hello everyone!
I'm building the book list app with React.
Could you tell me how I can create redux store in React?

**Comment by happyguydev** [comment]
Hi @cleverjack !
You can create a redux store like this.

import { configureStore } from '@reduxjs/toolkit';

export const store = configureStore({
  reducer: {
    counter: ...,
  },
});

**Comment by cleverjack** [comment]
@happyguydev 
Thanks for your kind help.
That works for me.
